name: " 🚥  - Run build locally"

on:
  workflow_dispatch:

jobs:
  build:
    name: Build with Maven
    runs-on: self-hosted

    steps:

      - name: "🚥 - Running State"
        run: |
          curl --location --request PUT '${{secrets.NANOLEAF_ADDRESS}}/state/' --data-raw '{"sat" : {"value": 0}, "hue": {"value" : 0 }}'
          curl --location --request PUT '${{secrets.NANOLEAF_ADDRESS}}/state/' --data-raw '{"sat" : {"value": 100}, "hue": {"value" : 30 }}'
        shell: bash


      - name: Checkout
        uses: actions/checkout@v2
  


      - name: Maven Build Test and Package
        id: maven_build
        run: |
          mvn package -B \
            -Dsha1="${{ steps.build_params.outputs.maven_sha1 }}" \
            -Dchangelist="${{ steps.build_params.outputs.maven_changelist }}" \
            -Dgithub.repository="${{ steps.build_params.outputs.github_repository }}"
        shell: bash

      - name: Copy Locally
        id: copy_jar
        run: |
          mkdir -p ~/to_delete/artifacts
          cp ./target/*.jar ~/to_delete/artifacts

      - name: "🚥 - Running State End"
        run: |
          curl --location --request PUT '${{secrets.NANOLEAF_ADDRESS}}/state/' --data-raw '{"sat" : {"value": 90}, "hue": {"value" : 120  }, "brightness" : {"value" : 60, "duration" : 5 }}'