name: 📦 - Publish Documentation with GitHub Pages
on:
  release:
    types: [created]


jobs:
  publish-release:
    name: Publish Release Documentation
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages      

      - id: refresh-gh-pages
        name: "Refresh Doc Branch"
        run: |
          git remote -v
          git branch
          git rebase origin/main
          git push origin gh-pages          
          


